filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx
repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: jx3
  url: https://storage.googleapis.com/jenkinsxio/charts
- name: stable
  url: https://charts.helm.sh/stable
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
releases:
- chart: bitnami/external-dns
  version: 4.5.0
  condition: jxRequirementsIngressExternalDNS.enabled
  name: external-dns
  values:
  - ../../versionStream/charts/bitnami/external-dns/values.yaml.gotmpl
  - jx-values.yaml
- chart: jx3/acme
  version: 0.0.19
  condition: jxRequirementsIngressTLS.enabled
  name: acme-jx
  values:
  - ../../versionStream/charts/jx3/acme-jx/values.yaml.gotmpl
  - jx-values.yaml
- chart: jx3/jxboot-helmfile-resources
  version: 1.0.40
  name: jxboot-helmfile-resources
  values:
  - ../../versionStream/charts/jx3/jxboot-helmfile-resources/values.yaml.gotmpl
  - jx-values.yaml
- chart: jx3/jenkins-x-crds
  version: 3.0.5
  name: jenkins-x-crds
  values:
  - ../../versionStream/charts/jx3/jenkins-x-crds/values.yaml.gotmpl
  - jx-values.yaml
- chart: jx3/jx-kh-check
  version: 0.0.56
  condition: jxRequirementsKuberhealthy.enabled
  name: health-checks-jx
  values:
  - ../../versionStream/charts/jx3/health-checks-jx/values.yaml.gotmpl
  - jx-values.yaml
templates: {}
renderedvalues: {}
